package org.apache.commons.httpclient;

/* loaded from: commons-httpclient-3.1.jar:org/apache/commons/httpclient/Header.class */
public class Header extends NameValuePair {
    private boolean isAutogenerated;

    public Header() {
        this(null, null);
    }

    public Header(String name, String value) {
        super(name, value);
        this.isAutogenerated = false;
    }

    public Header(String name, String value, boolean isAutogenerated) {
        super(name, value);
        this.isAutogenerated = false;
        this.isAutogenerated = isAutogenerated;
    }

    public String toExternalForm() {
        return new StringBuffer().append(null == getName() ? "" : getName()).append(": ").append(null == getValue() ? "" : getValue()).append("\r\n").toString();
    }

    @Override // org.apache.commons.httpclient.NameValuePair
    public String toString() {
        return toExternalForm();
    }

    public HeaderElement[] getValues() throws HttpException {
        return HeaderElement.parse(getValue());
    }

    public HeaderElement[] getElements() {
        return HeaderElement.parseElements(getValue());
    }

    public boolean isAutogenerated() {
        return this.isAutogenerated;
    }
}
