package org.apache.poi.ddf;

import java.util.HashMap;
import java.util.Map;

/* loaded from: poi-3.17.jar:org/apache/poi/ddf/EscherProperties.class */
public final class EscherProperties {
    public static final short TRANSFORM__ROTATION = 4;
    public static final short PROTECTION__LOCKROTATION = 119;
    public static final short PROTECTION__LOCKASPECTRATIO = 120;
    public static final short PROTECTION__LOCKPOSITION = 121;
    public static final short PROTECTION__LOCKAGAINSTSELECT = 122;
    public static final short PROTECTION__LOCKCROPPING = 123;
    public static final short PROTECTION__LOCKVERTICES = 124;
    public static final short PROTECTION__LOCKTEXT = 125;
    public static final short PROTECTION__LOCKADJUSTHANDLES = 126;
    public static final short PROTECTION__LOCKAGAINSTGROUPING = 127;
    public static final short TEXT__TEXTID = 128;
    public static final short TEXT__TEXTLEFT = 129;
    public static final short TEXT__TEXTTOP = 130;
    public static final short TEXT__TEXTRIGHT = 131;
    public static final short TEXT__TEXTBOTTOM = 132;
    public static final short TEXT__WRAPTEXT = 133;
    public static final short TEXT__SCALETEXT = 134;
    public static final short TEXT__ANCHORTEXT = 135;
    public static final short TEXT__TEXTFLOW = 136;
    public static final short TEXT__FONTROTATION = 137;
    public static final short TEXT__IDOFNEXTSHAPE = 138;
    public static final short TEXT__BIDIR = 139;
    public static final short TEXT__SINGLECLICKSELECTS = 187;
    public static final short TEXT__USEHOSTMARGINS = 188;
    public static final short TEXT__ROTATETEXTWITHSHAPE = 189;
    public static final short TEXT__SIZESHAPETOFITTEXT = 190;
    public static final short TEXT__SIZE_TEXT_TO_FIT_SHAPE = 191;
    public static final short GEOTEXT__UNICODE = 192;
    public static final short GEOTEXT__RTFTEXT = 193;
    public static final short GEOTEXT__ALIGNMENTONCURVE = 194;
    public static final short GEOTEXT__DEFAULTPOINTSIZE = 195;
    public static final short GEOTEXT__TEXTSPACING = 196;
    public static final short GEOTEXT__FONTFAMILYNAME = 197;
    public static final short GEOTEXT__REVERSEROWORDER = 240;
    public static final short GEOTEXT__HASTEXTEFFECT = 241;
    public static final short GEOTEXT__ROTATECHARACTERS = 242;
    public static final short GEOTEXT__KERNCHARACTERS = 243;
    public static final short GEOTEXT__TIGHTORTRACK = 244;
    public static final short GEOTEXT__STRETCHTOFITSHAPE = 245;
    public static final short GEOTEXT__CHARBOUNDINGBOX = 246;
    public static final short GEOTEXT__SCALETEXTONPATH = 247;
    public static final short GEOTEXT__STRETCHCHARHEIGHT = 248;
    public static final short GEOTEXT__NOMEASUREALONGPATH = 249;
    public static final short GEOTEXT__BOLDFONT = 250;
    public static final short GEOTEXT__ITALICFONT = 251;
    public static final short GEOTEXT__UNDERLINEFONT = 252;
    public static final short GEOTEXT__SHADOWFONT = 253;
    public static final short GEOTEXT__SMALLCAPSFONT = 254;
    public static final short GEOTEXT__STRIKETHROUGHFONT = 255;
    public static final short BLIP__CROPFROMTOP = 256;
    public static final short BLIP__CROPFROMBOTTOM = 257;
    public static final short BLIP__CROPFROMLEFT = 258;
    public static final short BLIP__CROPFROMRIGHT = 259;
    public static final short BLIP__BLIPTODISPLAY = 260;
    public static final short BLIP__BLIPFILENAME = 261;
    public static final short BLIP__BLIPFLAGS = 262;
    public static final short BLIP__TRANSPARENTCOLOR = 263;
    public static final short BLIP__CONTRASTSETTING = 264;
    public static final short BLIP__BRIGHTNESSSETTING = 265;
    public static final short BLIP__GAMMA = 266;
    public static final short BLIP__PICTUREID = 267;
    public static final short BLIP__DOUBLEMOD = 268;
    public static final short BLIP__PICTUREFILLMOD = 269;
    public static final short BLIP__PICTURELINE = 270;
    public static final short BLIP__PRINTBLIP = 271;
    public static final short BLIP__PRINTBLIPFILENAME = 272;
    public static final short BLIP__PRINTFLAGS = 273;
    public static final short BLIP__NOHITTESTPICTURE = 316;
    public static final short BLIP__PICTUREGRAY = 317;
    public static final short BLIP__PICTUREBILEVEL = 318;
    public static final short BLIP__PICTUREACTIVE = 319;
    public static final short GEOMETRY__LEFT = 320;
    public static final short GEOMETRY__TOP = 321;
    public static final short GEOMETRY__RIGHT = 322;
    public static final short GEOMETRY__BOTTOM = 323;
    public static final short GEOMETRY__SHAPEPATH = 324;
    public static final short GEOMETRY__VERTICES = 325;
    public static final short GEOMETRY__SEGMENTINFO = 326;
    public static final short GEOMETRY__ADJUSTVALUE = 327;
    public static final short GEOMETRY__ADJUST2VALUE = 328;
    public static final short GEOMETRY__ADJUST3VALUE = 329;
    public static final short GEOMETRY__ADJUST4VALUE = 330;
    public static final short GEOMETRY__ADJUST5VALUE = 331;
    public static final short GEOMETRY__ADJUST6VALUE = 332;
    public static final short GEOMETRY__ADJUST7VALUE = 333;
    public static final short GEOMETRY__ADJUST8VALUE = 334;
    public static final short GEOMETRY__ADJUST9VALUE = 335;
    public static final short GEOMETRY__ADJUST10VALUE = 336;
    public static final short GEOMETRY__SHADOWok = 378;
    public static final short GEOMETRY__3DOK = 379;
    public static final short GEOMETRY__LINEOK = 380;
    public static final short GEOMETRY__GEOTEXTOK = 381;
    public static final short GEOMETRY__FILLSHADESHAPEOK = 382;
    public static final short GEOMETRY__FILLOK = 383;
    public static final short FILL__FILLTYPE = 384;
    public static final short FILL__FILLCOLOR = 385;
    public static final short FILL__FILLOPACITY = 386;
    public static final short FILL__FILLBACKCOLOR = 387;
    public static final short FILL__BACKOPACITY = 388;
    public static final short FILL__CRMOD = 389;
    public static final short FILL__PATTERNTEXTURE = 390;
    public static final short FILL__BLIPFILENAME = 391;
    public static final short FILL__BLIPFLAGS = 392;
    public static final short FILL__WIDTH = 393;
    public static final short FILL__HEIGHT = 394;
    public static final short FILL__ANGLE = 395;
    public static final short FILL__FOCUS = 396;
    public static final short FILL__TOLEFT = 397;
    public static final short FILL__TOTOP = 398;
    public static final short FILL__TORIGHT = 399;
    public static final short FILL__TOBOTTOM = 400;
    public static final short FILL__RECTLEFT = 401;
    public static final short FILL__RECTTOP = 402;
    public static final short FILL__RECTRIGHT = 403;
    public static final short FILL__RECTBOTTOM = 404;
    public static final short FILL__DZTYPE = 405;
    public static final short FILL__SHADEPRESET = 406;
    public static final short FILL__SHADECOLORS = 407;
    public static final short FILL__ORIGINX = 408;
    public static final short FILL__ORIGINY = 409;
    public static final short FILL__SHAPEORIGINX = 410;
    public static final short FILL__SHAPEORIGINY = 411;
    public static final short FILL__SHADETYPE = 412;
    public static final short FILL__FILLED = 443;
    public static final short FILL__HITTESTFILL = 444;
    public static final short FILL__SHAPE = 445;
    public static final short FILL__USERECT = 446;
    public static final short FILL__NOFILLHITTEST = 447;
    public static final short LINESTYLE__COLOR = 448;
    public static final short LINESTYLE__OPACITY = 449;
    public static final short LINESTYLE__BACKCOLOR = 450;
    public static final short LINESTYLE__CRMOD = 451;
    public static final short LINESTYLE__LINETYPE = 452;
    public static final short LINESTYLE__FILLBLIP = 453;
    public static final short LINESTYLE__FILLBLIPNAME = 454;
    public static final short LINESTYLE__FILLBLIPFLAGS = 455;
    public static final short LINESTYLE__FILLWIDTH = 456;
    public static final short LINESTYLE__FILLHEIGHT = 457;
    public static final short LINESTYLE__FILLDZTYPE = 458;
    public static final short LINESTYLE__LINEWIDTH = 459;
    public static final short LINESTYLE__LINEMITERLIMIT = 460;
    public static final short LINESTYLE__LINESTYLE = 461;
    public static final short LINESTYLE__LINEDASHING = 462;
    public static final short LINESTYLE__LINEDASHSTYLE = 463;
    public static final short LINESTYLE__LINESTARTARROWHEAD = 464;
    public static final short LINESTYLE__LINEENDARROWHEAD = 465;
    public static final short LINESTYLE__LINESTARTARROWWIDTH = 466;
    public static final short LINESTYLE__LINESTARTARROWLENGTH = 467;
    public static final short LINESTYLE__LINEENDARROWWIDTH = 468;
    public static final short LINESTYLE__LINEENDARROWLENGTH = 469;
    public static final short LINESTYLE__LINEJOINSTYLE = 470;
    public static final short LINESTYLE__LINEENDCAPSTYLE = 471;
    public static final short LINESTYLE__ARROWHEADSOK = 507;
    public static final short LINESTYLE__ANYLINE = 508;
    public static final short LINESTYLE__HITLINETEST = 509;
    public static final short LINESTYLE__LINEFILLSHAPE = 510;
    public static final short LINESTYLE__NOLINEDRAWDASH = 511;
    public static final short LINESTYLE__NOLINEDRAWDASH_LEFT = 1407;
    public static final short LINESTYLE__NOLINEDRAWDASH_TOP = 1471;
    public static final short LINESTYLE__NOLINEDRAWDASH_BOTTOM = 1599;
    public static final short LINESTYLE__NOLINEDRAWDASH_RIGHT = 1535;
    public static final short SHADOWSTYLE__TYPE = 512;
    public static final short SHADOWSTYLE__COLOR = 513;
    public static final short SHADOWSTYLE__HIGHLIGHT = 514;
    public static final short SHADOWSTYLE__CRMOD = 515;
    public static final short SHADOWSTYLE__OPACITY = 516;
    public static final short SHADOWSTYLE__OFFSETX = 517;
    public static final short SHADOWSTYLE__OFFSETY = 518;
    public static final short SHADOWSTYLE__SECONDOFFSETX = 519;
    public static final short SHADOWSTYLE__SECONDOFFSETY = 520;
    public static final short SHADOWSTYLE__SCALEXTOX = 521;
    public static final short SHADOWSTYLE__SCALEYTOX = 522;
    public static final short SHADOWSTYLE__SCALEXTOY = 523;
    public static final short SHADOWSTYLE__SCALEYTOY = 524;
    public static final short SHADOWSTYLE__PERSPECTIVEX = 525;
    public static final short SHADOWSTYLE__PERSPECTIVEY = 526;
    public static final short SHADOWSTYLE__WEIGHT = 527;
    public static final short SHADOWSTYLE__ORIGINX = 528;
    public static final short SHADOWSTYLE__ORIGINY = 529;
    public static final short SHADOWSTYLE__SHADOW = 574;
    public static final short SHADOWSTYLE__SHADOWOBSURED = 575;
    public static final short PERSPECTIVE__TYPE = 576;
    public static final short PERSPECTIVE__OFFSETX = 577;
    public static final short PERSPECTIVE__OFFSETY = 578;
    public static final short PERSPECTIVE__SCALEXTOX = 579;
    public static final short PERSPECTIVE__SCALEYTOX = 580;
    public static final short PERSPECTIVE__SCALEXTOY = 581;
    public static final short PERSPECTIVE__SCALEYTOY = 582;
    public static final short PERSPECTIVE__PERSPECTIVEX = 583;
    public static final short PERSPECTIVE__PERSPECTIVEY = 584;
    public static final short PERSPECTIVE__WEIGHT = 585;
    public static final short PERSPECTIVE__ORIGINX = 586;
    public static final short PERSPECTIVE__ORIGINY = 587;
    public static final short PERSPECTIVE__PERSPECTIVEON = 639;
    public static final short THREED__SPECULARAMOUNT = 640;
    public static final short THREED__DIFFUSEAMOUNT = 661;
    public static final short THREED__SHININESS = 662;
    public static final short THREED__EDGETHICKNESS = 663;
    public static final short THREED__EXTRUDEFORWARD = 664;
    public static final short THREED__EXTRUDEBACKWARD = 665;
    public static final short THREED__EXTRUDEPLANE = 666;
    public static final short THREED__EXTRUSIONCOLOR = 667;
    public static final short THREED__CRMOD = 648;
    public static final short THREED__3DEFFECT = 700;
    public static final short THREED__METALLIC = 701;
    public static final short THREED__USEEXTRUSIONCOLOR = 702;
    public static final short THREED__LIGHTFACE = 703;
    public static final short THREEDSTYLE__YROTATIONANGLE = 704;
    public static final short THREEDSTYLE__XROTATIONANGLE = 705;
    public static final short THREEDSTYLE__ROTATIONAXISX = 706;
    public static final short THREEDSTYLE__ROTATIONAXISY = 707;
    public static final short THREEDSTYLE__ROTATIONAXISZ = 708;
    public static final short THREEDSTYLE__ROTATIONANGLE = 709;
    public static final short THREEDSTYLE__ROTATIONCENTERX = 710;
    public static final short THREEDSTYLE__ROTATIONCENTERY = 711;
    public static final short THREEDSTYLE__ROTATIONCENTERZ = 712;
    public static final short THREEDSTYLE__RENDERMODE = 713;
    public static final short THREEDSTYLE__TOLERANCE = 714;
    public static final short THREEDSTYLE__XVIEWPOINT = 715;
    public static final short THREEDSTYLE__YVIEWPOINT = 716;
    public static final short THREEDSTYLE__ZVIEWPOINT = 717;
    public static final short THREEDSTYLE__ORIGINX = 718;
    public static final short THREEDSTYLE__ORIGINY = 719;
    public static final short THREEDSTYLE__SKEWANGLE = 720;
    public static final short THREEDSTYLE__SKEWAMOUNT = 721;
    public static final short THREEDSTYLE__AMBIENTINTENSITY = 722;
    public static final short THREEDSTYLE__KEYX = 723;
    public static final short THREEDSTYLE__KEYY = 724;
    public static final short THREEDSTYLE__KEYZ = 725;
    public static final short THREEDSTYLE__KEYINTENSITY = 726;
    public static final short THREEDSTYLE__FILLX = 727;
    public static final short THREEDSTYLE__FILLY = 728;
    public static final short THREEDSTYLE__FILLZ = 729;
    public static final short THREEDSTYLE__FILLINTENSITY = 730;
    public static final short THREEDSTYLE__CONSTRAINROTATION = 763;
    public static final short THREEDSTYLE__ROTATIONCENTERAUTO = 764;
    public static final short THREEDSTYLE__PARALLEL = 765;
    public static final short THREEDSTYLE__KEYHARSH = 766;
    public static final short THREEDSTYLE__FILLHARSH = 767;
    public static final short SHAPE__MASTER = 769;
    public static final short SHAPE__CONNECTORSTYLE = 771;
    public static final short SHAPE__BLACKANDWHITESETTINGS = 772;
    public static final short SHAPE__WMODEPUREBW = 773;
    public static final short SHAPE__WMODEBW = 774;
    public static final short SHAPE__OLEICON = 826;
    public static final short SHAPE__PREFERRELATIVERESIZE = 827;
    public static final short SHAPE__LOCKSHAPETYPE = 828;
    public static final short SHAPE__DELETEATTACHEDOBJECT = 830;
    public static final short SHAPE__BACKGROUNDSHAPE = 831;
    public static final short CALLOUT__CALLOUTTYPE = 832;
    public static final short CALLOUT__XYCALLOUTGAP = 833;
    public static final short CALLOUT__CALLOUTANGLE = 834;
    public static final short CALLOUT__CALLOUTDROPTYPE = 835;
    public static final short CALLOUT__CALLOUTDROPSPECIFIED = 836;
    public static final short CALLOUT__CALLOUTLENGTHSPECIFIED = 837;
    public static final short CALLOUT__ISCALLOUT = 889;
    public static final short CALLOUT__CALLOUTACCENTBAR = 890;
    public static final short CALLOUT__CALLOUTTEXTBORDER = 891;
    public static final short CALLOUT__CALLOUTMINUSX = 892;
    public static final short CALLOUT__CALLOUTMINUSY = 893;
    public static final short CALLOUT__DROPAUTO = 894;
    public static final short CALLOUT__LENGTHSPECIFIED = 895;
    public static final short GROUPSHAPE__SHAPENAME = 896;
    public static final short GROUPSHAPE__DESCRIPTION = 897;
    public static final short GROUPSHAPE__HYPERLINK = 898;
    public static final short GROUPSHAPE__WRAPPOLYGONVERTICES = 899;
    public static final short GROUPSHAPE__WRAPDISTLEFT = 900;
    public static final short GROUPSHAPE__WRAPDISTTOP = 901;
    public static final short GROUPSHAPE__WRAPDISTRIGHT = 902;
    public static final short GROUPSHAPE__WRAPDISTBOTTOM = 903;
    public static final short GROUPSHAPE__REGROUPID = 904;
    public static final short GROUPSHAPE__UNUSED906 = 906;
    public static final short GROUPSHAPE__TOOLTIP = 909;
    public static final short GROUPSHAPE__SCRIPT = 910;
    public static final short GROUPSHAPE__POSH = 911;
    public static final short GROUPSHAPE__POSRELH = 912;
    public static final short GROUPSHAPE__POSV = 913;
    public static final short GROUPSHAPE__POSRELV = 914;
    public static final short GROUPSHAPE__HR_PCT = 915;
    public static final short GROUPSHAPE__HR_ALIGN = 916;
    public static final short GROUPSHAPE__HR_HEIGHT = 917;
    public static final short GROUPSHAPE__HR_WIDTH = 918;
    public static final short GROUPSHAPE__SCRIPTEXT = 919;
    public static final short GROUPSHAPE__SCRIPTLANG = 920;
    public static final short GROUPSHAPE__BORDERTOPCOLOR = 923;
    public static final short GROUPSHAPE__BORDERLEFTCOLOR = 924;
    public static final short GROUPSHAPE__BORDERBOTTOMCOLOR = 925;
    public static final short GROUPSHAPE__BORDERRIGHTCOLOR = 926;
    public static final short GROUPSHAPE__TABLEPROPERTIES = 927;
    public static final short GROUPSHAPE__TABLEROWPROPERTIES = 928;
    public static final short GROUPSHAPE__WEBBOT = 933;
    public static final short GROUPSHAPE__METROBLOB = 937;
    public static final short GROUPSHAPE__ZORDER = 938;
    public static final short GROUPSHAPE__FLAGS = 959;
    public static final short GROUPSHAPE__EDITEDWRAP = 953;
    public static final short GROUPSHAPE__BEHINDDOCUMENT = 954;
    public static final short GROUPSHAPE__ONDBLCLICKNOTIFY = 955;
    public static final short GROUPSHAPE__ISBUTTON = 956;
    public static final short GROUPSHAPE__1DADJUSTMENT = 957;
    public static final short GROUPSHAPE__HIDDEN = 958;
    public static final short GROUPSHAPE__PRINT = 959;
    private static final Map<Short, EscherPropertyMetaData> properties = initProps();

    private static Map<Short, EscherPropertyMetaData> initProps() {
        Map<Short, EscherPropertyMetaData> m = new HashMap<>();
        addProp(m, 4, "transform.rotation");
        addProp(m, 119, "protection.lockrotation");
        addProp(m, 120, "protection.lockaspectratio");
        addProp(m, 121, "protection.lockposition");
        addProp(m, 122, "protection.lockagainstselect");
        addProp(m, 123, "protection.lockcropping");
        addProp(m, 124, "protection.lockvertices");
        addProp(m, 125, "protection.locktext");
        addProp(m, 126, "protection.lockadjusthandles");
        addProp(m, 127, "protection.lockagainstgrouping", (byte) 1);
        addProp(m, 128, "text.textid");
        addProp(m, 129, "text.textleft");
        addProp(m, 130, "text.texttop");
        addProp(m, 131, "text.textright");
        addProp(m, 132, "text.textbottom");
        addProp(m, 133, "text.wraptext");
        addProp(m, 134, "text.scaletext");
        addProp(m, 135, "text.anchortext");
        addProp(m, 136, "text.textflow");
        addProp(m, 137, "text.fontrotation");
        addProp(m, 138, "text.idofnextshape");
        addProp(m, 139, "text.bidir");
        addProp(m, 187, "text.singleclickselects");
        addProp(m, 188, "text.usehostmargins");
        addProp(m, 189, "text.rotatetextwithshape");
        addProp(m, 190, "text.sizeshapetofittext");
        addProp(m, 191, "text.sizetexttofitshape", (byte) 1);
        addProp(m, 192, "geotext.unicode");
        addProp(m, 193, "geotext.rtftext");
        addProp(m, 194, "geotext.alignmentoncurve");
        addProp(m, 195, "geotext.defaultpointsize");
        addProp(m, 196, "geotext.textspacing");
        addProp(m, 197, "geotext.fontfamilyname");
        addProp(m, 240, "geotext.reverseroworder");
        addProp(m, GEOTEXT__HASTEXTEFFECT, "geotext.hastexteffect");
        addProp(m, GEOTEXT__ROTATECHARACTERS, "geotext.rotatecharacters");
        addProp(m, GEOTEXT__KERNCHARACTERS, "geotext.kerncharacters");
        addProp(m, GEOTEXT__TIGHTORTRACK, "geotext.tightortrack");
        addProp(m, GEOTEXT__STRETCHTOFITSHAPE, "geotext.stretchtofitshape");
        addProp(m, GEOTEXT__CHARBOUNDINGBOX, "geotext.charboundingbox");
        addProp(m, 247, "geotext.scaletextonpath");
        addProp(m, GEOTEXT__STRETCHCHARHEIGHT, "geotext.stretchcharheight");
        addProp(m, GEOTEXT__NOMEASUREALONGPATH, "geotext.nomeasurealongpath");
        addProp(m, GEOTEXT__BOLDFONT, "geotext.boldfont");
        addProp(m, 251, "geotext.italicfont");
        addProp(m, 252, "geotext.underlinefont");
        addProp(m, 253, "geotext.shadowfont");
        addProp(m, 254, "geotext.smallcapsfont");
        addProp(m, 255, "geotext.strikethroughfont");
        addProp(m, 256, "blip.cropfromtop");
        addProp(m, 257, "blip.cropfrombottom");
        addProp(m, 258, "blip.cropfromleft");
        addProp(m, 259, "blip.cropfromright");
        addProp(m, 260, "blip.bliptodisplay");
        addProp(m, 261, "blip.blipfilename");
        addProp(m, 262, "blip.blipflags");
        addProp(m, 263, "blip.transparentcolor");
        addProp(m, 264, "blip.contrastsetting");
        addProp(m, 265, "blip.brightnesssetting");
        addProp(m, 266, "blip.gamma");
        addProp(m, 267, "blip.pictureid");
        addProp(m, 268, "blip.doublemod");
        addProp(m, 269, "blip.picturefillmod");
        addProp(m, 270, "blip.pictureline");
        addProp(m, 271, "blip.printblip");
        addProp(m, 272, "blip.printblipfilename");
        addProp(m, 273, "blip.printflags");
        addProp(m, 316, "blip.nohittestpicture");
        addProp(m, 317, "blip.picturegray");
        addProp(m, 318, "blip.picturebilevel");
        addProp(m, 319, "blip.pictureactive");
        addProp(m, 320, "geometry.left");
        addProp(m, 321, "geometry.top");
        addProp(m, 322, "geometry.right");
        addProp(m, 323, "geometry.bottom");
        addProp(m, 324, "geometry.shapepath", (byte) 3);
        addProp(m, 325, "geometry.vertices", (byte) 5);
        addProp(m, 326, "geometry.segmentinfo", (byte) 5);
        addProp(m, 327, "geometry.adjustvalue");
        addProp(m, 328, "geometry.adjust2value");
        addProp(m, 329, "geometry.adjust3value");
        addProp(m, 330, "geometry.adjust4value");
        addProp(m, 331, "geometry.adjust5value");
        addProp(m, 332, "geometry.adjust6value");
        addProp(m, 333, "geometry.adjust7value");
        addProp(m, 334, "geometry.adjust8value");
        addProp(m, 335, "geometry.adjust9value");
        addProp(m, 336, "geometry.adjust10value");
        addProp(m, 378, "geometry.shadowOK");
        addProp(m, GEOMETRY__3DOK, "geometry.3dok");
        addProp(m, GEOMETRY__LINEOK, "geometry.lineok");
        addProp(m, GEOMETRY__GEOTEXTOK, "geometry.geotextok");
        addProp(m, GEOMETRY__FILLSHADESHAPEOK, "geometry.fillshadeshapeok");
        addProp(m, 383, "geometry.fillok", (byte) 1);
        addProp(m, 384, "fill.filltype");
        addProp(m, FILL__FILLCOLOR, "fill.fillcolor", (byte) 2);
        addProp(m, FILL__FILLOPACITY, "fill.fillopacity");
        addProp(m, FILL__FILLBACKCOLOR, "fill.fillbackcolor", (byte) 2);
        addProp(m, FILL__BACKOPACITY, "fill.backopacity");
        addProp(m, FILL__CRMOD, "fill.crmod");
        addProp(m, FILL__PATTERNTEXTURE, "fill.patterntexture");
        addProp(m, FILL__BLIPFILENAME, "fill.blipfilename");
        addProp(m, FILL__BLIPFLAGS, "fill.blipflags");
        addProp(m, FILL__WIDTH, "fill.width");
        addProp(m, FILL__HEIGHT, "fill.height");
        addProp(m, FILL__ANGLE, "fill.angle");
        addProp(m, FILL__FOCUS, "fill.focus");
        addProp(m, FILL__TOLEFT, "fill.toleft");
        addProp(m, FILL__TOTOP, "fill.totop");
        addProp(m, FILL__TORIGHT, "fill.toright");
        addProp(m, 400, "fill.tobottom");
        addProp(m, 401, "fill.rectleft");
        addProp(m, 402, "fill.recttop");
        addProp(m, 403, "fill.rectright");
        addProp(m, 404, "fill.rectbottom");
        addProp(m, 405, "fill.dztype");
        addProp(m, 406, "fill.shadepreset");
        addProp(m, 407, "fill.shadecolors", (byte) 5);
        addProp(m, 408, "fill.originx");
        addProp(m, 409, "fill.originy");
        addProp(m, 410, "fill.shapeoriginx");
        addProp(m, 411, "fill.shapeoriginy");
        addProp(m, 412, "fill.shadetype");
        addProp(m, 443, "fill.filled");
        addProp(m, 444, "fill.hittestfill");
        addProp(m, FILL__SHAPE, "fill.shape");
        addProp(m, 446, "fill.userect");
        addProp(m, FILL__NOFILLHITTEST, "fill.nofillhittest", (byte) 1);
        addProp(m, LINESTYLE__COLOR, "linestyle.color", (byte) 2);
        addProp(m, 449, "linestyle.opacity");
        addProp(m, LINESTYLE__BACKCOLOR, "linestyle.backcolor", (byte) 2);
        addProp(m, LINESTYLE__CRMOD, "linestyle.crmod");
        addProp(m, LINESTYLE__LINETYPE, "linestyle.linetype");
        addProp(m, LINESTYLE__FILLBLIP, "linestyle.fillblip");
        addProp(m, LINESTYLE__FILLBLIPNAME, "linestyle.fillblipname");
        addProp(m, LINESTYLE__FILLBLIPFLAGS, "linestyle.fillblipflags");
        addProp(m, LINESTYLE__FILLWIDTH, "linestyle.fillwidth");
        addProp(m, LINESTYLE__FILLHEIGHT, "linestyle.fillheight");
        addProp(m, LINESTYLE__FILLDZTYPE, "linestyle.filldztype");
        addProp(m, LINESTYLE__LINEWIDTH, "linestyle.linewidth");
        addProp(m, LINESTYLE__LINEMITERLIMIT, "linestyle.linemiterlimit");
        addProp(m, LINESTYLE__LINESTYLE, "linestyle.linestyle");
        addProp(m, LINESTYLE__LINEDASHING, "linestyle.linedashing");
        addProp(m, LINESTYLE__LINEDASHSTYLE, "linestyle.linedashstyle", (byte) 5);
        addProp(m, LINESTYLE__LINESTARTARROWHEAD, "linestyle.linestartarrowhead");
        addProp(m, LINESTYLE__LINEENDARROWHEAD, "linestyle.lineendarrowhead");
        addProp(m, LINESTYLE__LINESTARTARROWWIDTH, "linestyle.linestartarrowwidth");
        addProp(m, LINESTYLE__LINESTARTARROWLENGTH, "linestyle.linestartarrowlength");
        addProp(m, LINESTYLE__LINEENDARROWWIDTH, "linestyle.lineendarrowwidth");
        addProp(m, LINESTYLE__LINEENDARROWLENGTH, "linestyle.lineendarrowlength");
        addProp(m, LINESTYLE__LINEJOINSTYLE, "linestyle.linejoinstyle");
        addProp(m, LINESTYLE__LINEENDCAPSTYLE, "linestyle.lineendcapstyle");
        addProp(m, 507, "linestyle.arrowheadsok");
        addProp(m, 508, "linestyle.anyline");
        addProp(m, LINESTYLE__HITLINETEST, "linestyle.hitlinetest");
        addProp(m, LINESTYLE__LINEFILLSHAPE, "linestyle.linefillshape");
        addProp(m, 511, "linestyle.nolinedrawdash", (byte) 1);
        addProp(m, 1407, "linestyle.nolinedrawdash.left", (byte) 1);
        addProp(m, 1471, "linestyle.nolinedrawdash.top", (byte) 1);
        addProp(m, 1599, "linestyle.nolinedrawdash.bottom", (byte) 1);
        addProp(m, 1535, "linestyle.nolinedrawdash.right", (byte) 1);
        addProp(m, 512, "shadowstyle.type");
        addProp(m, 513, "shadowstyle.color", (byte) 2);
        addProp(m, 514, "shadowstyle.highlight");
        addProp(m, 515, "shadowstyle.crmod");
        addProp(m, 516, "shadowstyle.opacity");
        addProp(m, 517, "shadowstyle.offsetx");
        addProp(m, 518, "shadowstyle.offsety");
        addProp(m, 519, "shadowstyle.secondoffsetx");
        addProp(m, 520, "shadowstyle.secondoffsety");
        addProp(m, 521, "shadowstyle.scalextox");
        addProp(m, 522, "shadowstyle.scaleytox");
        addProp(m, 523, "shadowstyle.scalextoy");
        addProp(m, 524, "shadowstyle.scaleytoy");
        addProp(m, 525, "shadowstyle.perspectivex");
        addProp(m, 526, "shadowstyle.perspectivey");
        addProp(m, 527, "shadowstyle.weight");
        addProp(m, 528, "shadowstyle.originx");
        addProp(m, 529, "shadowstyle.originy");
        addProp(m, 574, "shadowstyle.shadow");
        addProp(m, 575, "shadowstyle.shadowobscured");
        addProp(m, 576, "perspective.type");
        addProp(m, 577, "perspective.offsetx");
        addProp(m, PERSPECTIVE__OFFSETY, "perspective.offsety");
        addProp(m, PERSPECTIVE__SCALEXTOX, "perspective.scalextox");
        addProp(m, PERSPECTIVE__SCALEYTOX, "perspective.scaleytox");
        addProp(m, PERSPECTIVE__SCALEXTOY, "perspective.scalextoy");
        addProp(m, 582, "perspective.scaleytoy");
        addProp(m, PERSPECTIVE__PERSPECTIVEX, "perspective.perspectivex");
        addProp(m, PERSPECTIVE__PERSPECTIVEY, "perspective.perspectivey");
        addProp(m, PERSPECTIVE__WEIGHT, "perspective.weight");
        addProp(m, PERSPECTIVE__ORIGINX, "perspective.originx");
        addProp(m, 587, "perspective.originy");
        addProp(m, PERSPECTIVE__PERSPECTIVEON, "perspective.perspectiveon");
        addProp(m, 640, "3d.specularamount");
        addProp(m, THREED__DIFFUSEAMOUNT, "3d.diffuseamount");
        addProp(m, 662, "3d.shininess");
        addProp(m, 663, "3d.edgethickness");
        addProp(m, 664, "3d.extrudeforward");
        addProp(m, 665, "3d.extrudebackward");
        addProp(m, 666, "3d.extrudeplane");
        addProp(m, THREED__EXTRUSIONCOLOR, "3d.extrusioncolor", (byte) 2);
        addProp(m, THREED__CRMOD, "3d.crmod");
        addProp(m, 700, "3d.3deffect");
        addProp(m, THREED__METALLIC, "3d.metallic");
        addProp(m, THREED__USEEXTRUSIONCOLOR, "3d.useextrusioncolor", (byte) 2);
        addProp(m, THREED__LIGHTFACE, "3d.lightface");
        addProp(m, THREEDSTYLE__YROTATIONANGLE, "3dstyle.yrotationangle");
        addProp(m, THREEDSTYLE__XROTATIONANGLE, "3dstyle.xrotationangle");
        addProp(m, THREEDSTYLE__ROTATIONAXISX, "3dstyle.rotationaxisx");
        addProp(m, THREEDSTYLE__ROTATIONAXISY, "3dstyle.rotationaxisy");
        addProp(m, THREEDSTYLE__ROTATIONAXISZ, "3dstyle.rotationaxisz");
        addProp(m, THREEDSTYLE__ROTATIONANGLE, "3dstyle.rotationangle");
        addProp(m, THREEDSTYLE__ROTATIONCENTERX, "3dstyle.rotationcenterx");
        addProp(m, THREEDSTYLE__ROTATIONCENTERY, "3dstyle.rotationcentery");
        addProp(m, 712, "3dstyle.rotationcenterz");
        addProp(m, 713, "3dstyle.rendermode");
        addProp(m, 714, "3dstyle.tolerance");
        addProp(m, THREEDSTYLE__XVIEWPOINT, "3dstyle.xviewpoint");
        addProp(m, THREEDSTYLE__YVIEWPOINT, "3dstyle.yviewpoint");
        addProp(m, THREEDSTYLE__ZVIEWPOINT, "3dstyle.zviewpoint");
        addProp(m, THREEDSTYLE__ORIGINX, "3dstyle.originx");
        addProp(m, THREEDSTYLE__ORIGINY, "3dstyle.originy");
        addProp(m, THREEDSTYLE__SKEWANGLE, "3dstyle.skewangle");
        addProp(m, THREEDSTYLE__SKEWAMOUNT, "3dstyle.skewamount");
        addProp(m, THREEDSTYLE__AMBIENTINTENSITY, "3dstyle.ambientintensity");
        addProp(m, THREEDSTYLE__KEYX, "3dstyle.keyx");
        addProp(m, THREEDSTYLE__KEYY, "3dstyle.keyy");
        addProp(m, THREEDSTYLE__KEYZ, "3dstyle.keyz");
        addProp(m, THREEDSTYLE__KEYINTENSITY, "3dstyle.keyintensity");
        addProp(m, THREEDSTYLE__FILLX, "3dstyle.fillx");
        addProp(m, THREEDSTYLE__FILLY, "3dstyle.filly");
        addProp(m, THREEDSTYLE__FILLZ, "3dstyle.fillz");
        addProp(m, THREEDSTYLE__FILLINTENSITY, "3dstyle.fillintensity");
        addProp(m, 763, "3dstyle.constrainrotation");
        addProp(m, 764, "3dstyle.rotationcenterauto");
        addProp(m, THREEDSTYLE__PARALLEL, "3dstyle.parallel");
        addProp(m, THREEDSTYLE__KEYHARSH, "3dstyle.keyharsh");
        addProp(m, THREEDSTYLE__FILLHARSH, "3dstyle.fillharsh");
        addProp(m, 769, "shape.master");
        addProp(m, 771, "shape.connectorstyle");
        addProp(m, 772, "shape.blackandwhitesettings");
        addProp(m, 773, "shape.wmodepurebw");
        addProp(m, 774, "shape.wmodebw");
        addProp(m, SHAPE__OLEICON, "shape.oleicon");
        addProp(m, SHAPE__PREFERRELATIVERESIZE, "shape.preferrelativeresize");
        addProp(m, SHAPE__LOCKSHAPETYPE, "shape.lockshapetype");
        addProp(m, SHAPE__DELETEATTACHEDOBJECT, "shape.deleteattachedobject");
        addProp(m, SHAPE__BACKGROUNDSHAPE, "shape.backgroundshape");
        addProp(m, 832, "callout.callouttype");
        addProp(m, CALLOUT__XYCALLOUTGAP, "callout.xycalloutgap");
        addProp(m, CALLOUT__CALLOUTANGLE, "callout.calloutangle");
        addProp(m, CALLOUT__CALLOUTDROPTYPE, "callout.calloutdroptype");
        addProp(m, CALLOUT__CALLOUTDROPSPECIFIED, "callout.calloutdropspecified");
        addProp(m, CALLOUT__CALLOUTLENGTHSPECIFIED, "callout.calloutlengthspecified");
        addProp(m, CALLOUT__ISCALLOUT, "callout.iscallout");
        addProp(m, CALLOUT__CALLOUTACCENTBAR, "callout.calloutaccentbar");
        addProp(m, CALLOUT__CALLOUTTEXTBORDER, "callout.callouttextborder");
        addProp(m, CALLOUT__CALLOUTMINUSX, "callout.calloutminusx");
        addProp(m, CALLOUT__CALLOUTMINUSY, "callout.calloutminusy");
        addProp(m, CALLOUT__DROPAUTO, "callout.dropauto");
        addProp(m, CALLOUT__LENGTHSPECIFIED, "callout.lengthspecified");
        addProp(m, GROUPSHAPE__SHAPENAME, "groupshape.shapename");
        addProp(m, GROUPSHAPE__DESCRIPTION, "groupshape.description");
        addProp(m, GROUPSHAPE__HYPERLINK, "groupshape.hyperlink");
        addProp(m, GROUPSHAPE__WRAPPOLYGONVERTICES, "groupshape.wrappolygonvertices", (byte) 5);
        addProp(m, 900, "groupshape.wrapdistleft");
        addProp(m, 901, "groupshape.wrapdisttop");
        addProp(m, GROUPSHAPE__WRAPDISTRIGHT, "groupshape.wrapdistright");
        addProp(m, 903, "groupshape.wrapdistbottom");
        addProp(m, GROUPSHAPE__REGROUPID, "groupshape.regroupid");
        addProp(m, GROUPSHAPE__UNUSED906, "unused906");
        addProp(m, GROUPSHAPE__TOOLTIP, "groupshape.wzTooltip");
        addProp(m, 910, "groupshape.wzScript");
        addProp(m, GROUPSHAPE__POSH, "groupshape.posh");
        addProp(m, GROUPSHAPE__POSRELH, "groupshape.posrelh");
        addProp(m, GROUPSHAPE__POSV, "groupshape.posv");
        addProp(m, GROUPSHAPE__POSRELV, "groupshape.posrelv");
        addProp(m, GROUPSHAPE__HR_PCT, "groupshape.pctHR");
        addProp(m, GROUPSHAPE__HR_ALIGN, "groupshape.alignHR");
        addProp(m, GROUPSHAPE__HR_HEIGHT, "groupshape.dxHeightHR");
        addProp(m, GROUPSHAPE__HR_WIDTH, "groupshape.dxWidthHR");
        addProp(m, GROUPSHAPE__SCRIPTEXT, "groupshape.wzScriptExtAttr");
        addProp(m, GROUPSHAPE__SCRIPTLANG, "groupshape.scriptLang");
        addProp(m, GROUPSHAPE__BORDERTOPCOLOR, "groupshape.borderTopColor");
        addProp(m, GROUPSHAPE__BORDERLEFTCOLOR, "groupshape.borderLeftColor");
        addProp(m, GROUPSHAPE__BORDERBOTTOMCOLOR, "groupshape.borderBottomColor");
        addProp(m, GROUPSHAPE__BORDERRIGHTCOLOR, "groupshape.borderRightColor");
        addProp(m, GROUPSHAPE__TABLEPROPERTIES, "groupshape.tableProperties");
        addProp(m, GROUPSHAPE__TABLEROWPROPERTIES, "groupshape.tableRowProperties", (byte) 5);
        addProp(m, GROUPSHAPE__WEBBOT, "groupshape.wzWebBot");
        addProp(m, GROUPSHAPE__METROBLOB, "groupshape.metroBlob");
        addProp(m, GROUPSHAPE__ZORDER, "groupshape.dhgt");
        addProp(m, 959, "groupshape.GroupShapeBooleanProperties");
        addProp(m, GROUPSHAPE__EDITEDWRAP, "groupshape.editedwrap");
        addProp(m, GROUPSHAPE__BEHINDDOCUMENT, "groupshape.behinddocument");
        addProp(m, GROUPSHAPE__ONDBLCLICKNOTIFY, "groupshape.ondblclicknotify");
        addProp(m, GROUPSHAPE__ISBUTTON, "groupshape.isbutton");
        addProp(m, GROUPSHAPE__1DADJUSTMENT, "groupshape.1dadjustment");
        addProp(m, GROUPSHAPE__HIDDEN, "groupshape.hidden");
        addProp(m, 959, "groupshape.print", (byte) 1);
        return m;
    }

    private static void addProp(Map<Short, EscherPropertyMetaData> m, int s, String propName) {
        m.put(Short.valueOf((short) s), new EscherPropertyMetaData(propName));
    }

    private static void addProp(Map<Short, EscherPropertyMetaData> m, int s, String propName, byte type) {
        m.put(Short.valueOf((short) s), new EscherPropertyMetaData(propName, type));
    }

    public static String getPropertyName(short propertyId) {
        EscherPropertyMetaData o = properties.get(Short.valueOf(propertyId));
        return o == null ? "unknown" : o.getDescription();
    }

    public static byte getPropertyType(short propertyId) {
        EscherPropertyMetaData escherPropertyMetaData = properties.get(Short.valueOf(propertyId));
        if (escherPropertyMetaData == null) {
            return (byte) 0;
        }
        return escherPropertyMetaData.getType();
    }
}
